### ISSUE TITLE
Could not find android:react-native-webview:unspecified.

### ISSUE THREAD

**Issue by sokolking** [mopinion/mopinion-sdk-android#1]
Hello,

We are using the Mopinion framework in our app, but we encountered a problem when tried to use the latest version.

When we follow to install instructions, android studio show next error:
![image](https://user-images.githubusercontent.com/13314954/112356604-cf648880-8cdf-11eb-8776-d1cac9af301b.png)

**project gradle:**

allprojects {
    repositories {
        google()
        jcenter()
        maven { url "$rootDir/node_modules/react-native/android" }
        maven { url "$rootDir/node_modules/jsc-android/dist" }
        maven { url "https://dl.bintray.com/mopinion/MopinionSDK" }
        maven { url "https://jitpack.io" }
    }
}

**app gradle:**

...

project.ext.react = [
        enableHermes: false,  // clean and rebuild if changing
]

def enableHermes = project.ext.react.get("enableHermes", false);
def jscFlavor = 'org.webkit:android-jsc:+'

...

    //mOpinion
    implementation "com.facebook.react:react-native:0.61.5"
    implementation project(':react-native-webview')
    implementation project(':@react-native-community_async-storage')
    implementation "com.mopinion.mopinionsdk:mopinionsdk:0.4.0"
    implementation "com.android.volley:volley:1.1.1"

...

**package.json:**

{
  "name": "MopinionSDK",
  "version": "0.1.0",
  "dependencies": {
    "@react-native-community/async-storage": "1.12.1",
    "react": "16.13.1",
    "react-native": "0.61.5",
    "react-native-webview": "^11.3.1"
  }
}

**Comment by Piethot** [comment]
Hi @sokolking,
We will provide you with an update through our Jira ticketing system as soon as we have investigated the issue further.
Kind regards,
Pieter
